name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CERTIFICATE_TEST_PASSWORD: ${{ secrets.CERTIFICATE_TEST_PASSWORD }}      

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: copy certificate
        run: |
          cd src/test_cert && 
          curl --header 'Authorization: token ${{ secrets.CERTIFICATE_ACCESS_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          --remote-name \
          --location ${{ secrets.CERTIFICATE_PRIVATE_REPOSITORY }}
      - run: cd src/test_cert && ls                   
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: rm -rf src/test_cert
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
